[build]
  publish = "public"
  command = "GATSBY_ACTIVE_ENV=staging yarn run build"

[context.production]
  command = "GATSBY_ACTIVE_ENV=production yarn run build:producton"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
