name: Submit Sitemap

on: deployment

jobs:
  google:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment hook
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://www.google.com/ping?sitemap=https://www.jamieburnip.dev/sitemap.xml"
          method: "GET"

  yandex:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment hook
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://webmaster.yandex.ru/ping?sitemap=https://www.jamieburnip.dev/sitemap.xml"
          method: "GET"
